/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Classes.Abstratas;

public class App {
    

    public static void main(String[] args) {
        
    Mobilia sofa = new Sofa("azul", "madeira");
        Mobilia mesa = new Mesa("preta", "metal");

        sofa.montar();  // Saída: Montando o sofá de cor azul feito de madeira.
        mesa.montar();  // Saída: Montando a mesa de cor preta feita de metal.
        sofa.desmontar(); // Saída: Desmontando a mobília.
  

    }
}
