/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Arrays;

public class App {
  
    public static void main(String[] args) {
        
// Declarando Array
        
        int[] numeros; // Declaração de um array de inteiros
        numeros = new int[5]; // Cria um array de inteiros com 5 elementos
        int[] numeros2 = {1, 2, 3, 4, 5}; // Inicializa o array com valores
        
        //Acessando array
        System.out.println(numeros[0]);
        int primeiroNumero = numeros[0]; // Acessa o primeiro elemento do array
        int segundoNumero = numeros[1]; // Acessa o segundo elemento do array
    
        //Modficando valores no array
        
        numeros[0] = 10; // Altera o primeiro elemento para 10
        System.out.println(numeros[0]);
        
        // Comprimento do array
        
        System.out.println(numeros.length);
        
        // Iterando sobre um Array
        
        //for (int i = 0; i < numeros.length; i++) {
        //System.out.println(numeros[i]); // Imprime cada elemento do array
        //}
        
        // Usando o Loop for-each
        
        //for(int numero5:numeros2) {
        //System.out.println(numero5); // Imprime cada elemento do array
//}
        
        String[] nomes = {"ana", "julia", "paulo", "je", "xuxa"};
        nomes[2] = "jobiscleison";
        
        for(String nomes4:nomes) {
        System.out.println(nomes4); // Imprime cada elemento do array
}
    }
}
