/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Compras;

public class App {

    public static void main(String[] args) {
        Mercado mercado = new Mercado();
        mercado.Start();
    }
}
