/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meuProjetoJava;

public class App {
    
    public static void main(String[] args){
    
    String nomeCachorro = "Danielle";// Caracteres
    int idadeCachorro = 20;  // Numeros inteiros
    double alturaCachorro = 1.10; //Numeros com decimais
    boolean seiJava = true; // Booleans
    char letraInicial = 'D'; // Apenas 1 caracter
    int numeroAleatorio = 29;
    int numeroAleatorio2 = 30;
    
    int resto = numeroAleatorio %2;
    System.out.println("Nome do cachorro: " + nomeCachorro + ", Idade do Cachorro: " + idadeCachorro + ", Altura do Cachorro: " + alturaCachorro);
    
    System.out.println(idadeCachorro + numeroAleatorio);
    
    System.out.println("media dos numeros: " + (idadeCachorro + numeroAleatorio + numeroAleatorio2 / 2));
  
    if(resto == 0){
        System.out.println("o numero é par!");
    }else{
        System.out.println("o numero não é par");
    }
    
}
}