/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aula2;

public class App {
    public static void main(String[] args) {
    /*String meuNome = "Danielle";
    int idade = 20;  // Numeros inteiros
    double altura = 1.65; //Numeros com decimais
        
        System.out.println("Meu nome e: " + meuNome);
        System.out.println("Meu idade e: " + idade);
        System.out.println("Meu altura e: " + altura);
    */
                                                                                                                                                    
    /*int numero = 5;
    if(numero > 0){
    System.out.println("o numero e positivo!");
    }else if(numero < 0){
    System.out.println("esse numero e negativo!");
    }else {
    System.out.println("esse numero e zero!");
    }
    */
    /*
    int numeroEscolhido = 4;
    switch (numeroEscolhido){
        case 1:
         System.out.println("segunda feira!");   
         break;
        case 2:
         System.out.println("terca feira!");
         break;
        case 3:
            System.out.println("quarta feira!");
            break;
        case 4:
            System.out.println("quinta feira!");
            break;
        case 5:
            System.out.println("sexta feira!");
            break;
        default:
            System.out.println("Nao compreendi!"); 
            break;
    }
    */
    
    int numero = 2024;
    int numero2 = 5;
    String resultado = (numero % 2 == 0) ? "par": "impar"; // if-else simplificado
            System.out.println("o numero e: " + resultado);
    
    String resultado2 = (numero > 0)? "maior": "menor"; // if-else simplificado
            System.out.println("o numero e: " + resultado2);
            
    String resultado3 = (18 >= numero) ? "menor": "maior"; // if-else simplificado
            System.out.println("o numero e: " + resultado3);
    
    String resultado4 = (numero > numero2) ? "A maior B": "B maior A"; // if-else simplificado
            System.out.println("o numero e: " + resultado4);
    
    String resultado5 = ((numero % 4 == 0 && numero % 100 != 0) || numero % 400 == 0) ? "bissexto": "nao bissexto"; // if-else simplificado
            System.out.println("o numero e: " + resultado5);
    
    }
}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

